// Generated by scripts/sync-design-tokens.mjs. Do not edit.
export const designTokens = Object.freeze({
  "breakpoints": {
    "xs": 320,
    "sm": 375,
    "md": 768,
    "lg": 1024,
    "xl": 1280,
    "2xl": 1440
  },
  "components": {
    "controlHeightPx": {
      "compact": 32,
      "default": 40,
      "comfortable": 44,
      "touch": 48
    },
    "iconSizePx": {
      "sm": 16,
      "md": 18,
      "lg": 20,
      "xl": 24
    },
    "tableRowHeightPx": {
      "compact": 40,
      "default": 48,
      "comfortable": 56
    },
    "navigationPx": {
      "adminSidebar": 232,
      "adminRail": 68,
      "websiteHeader": 72,
      "miniappTab": 50
    },
    "overlayPx": {
      "dialogSm": 420,
      "dialogMd": 560,
      "dialogLg": 720,
      "drawer": 520
    },
    "focus": {
      "widthPx": 3,
      "offsetPx": 2
    },
    "disabledOpacity": 0.48
  },
  "containers": {
    "reading": 720,
    "content": 1180,
    "wide": 1440
  },
  "motion": {
    "instant": 100,
    "fast": 160,
    "base": 220,
    "slow": 320
  },
  "patterns": {
    "musicTicketPx": {
      "notch": 8,
      "perforation": 4,
      "rule": 1,
      "dateRail": 58,
      "stub": 72
    },
    "editorialPx": {
      "mediaRadius": 6,
      "sectionGapMobile": 64,
      "sectionGapDesktop": 96,
      "heroMaxHeight": 760
    }
  },
  "semanticColors": {
    "primary": "#00754a",
    "primaryStrong": "#006241",
    "primaryPressed": "#004f3d",
    "primarySoft": "#d4e9e2",
    "primaryLine": "#9fc9bb",
    "primaryWash": "#f6faf8",
    "primarySurfaceOverlay": "rgba(255, 255, 255, 0.34)",
    "primaryDivider": "rgba(0, 98, 65, 0.14)",
    "onPrimary": "#ffffff",
    "onPrimaryMuted": "rgb(255 255 255 / 75%)",
    "onPrimaryFaint": "rgb(255 255 255 / 55%)",
    "onPrimaryDivider": "rgba(255, 255, 255, 0.3)",
    "onPrimaryOverlay": "rgb(255 255 255 / 12%)",
    "ink": "#31443e",
    "inkStrong": "#1e3932",
    "textSecondary": "#5f6f69",
    "textMuted": "#87928e",
    "canvas": "#f4f4f2",
    "surface": "#ffffff",
    "secondarySurface": "#edf4f1",
    "mutedSurface": "#eef3f1",
    "sidebarSurface": "#f0f6f3",
    "line": "#dededb",
    "lineStrong": "#b9b9b5",
    "lineTinted": "#d8e2de",
    "inputLine": "#c8d6d1",
    "focusRing": "#00754a",
    "blue": "#0079c8",
    "bluePressed": "#005f9e",
    "infoText": "#005f9e",
    "blueSoft": "#eaf5fc",
    "blueLine": "#b8d9ef",
    "blueLineStrong": "#9bc9e8",
    "blueWash": "#f7fbfe",
    "yellow": "#f5c400",
    "yellowPressed": "#d9a900",
    "yellowSoft": "#fff8d6",
    "gold": "#7d6200",
    "goldForeground": "#5f4a00",
    "goldLine": "#e4cf70",
    "goldWash": "#fffdf3",
    "success": "#1f7a4d",
    "successSoft": "#e8f5ed",
    "successLine": "#b9dcc8",
    "successWash": "#f7fbf8",
    "danger": "#b42318",
    "dangerPressed": "#8f1c14",
    "dangerSoft": "#fff0ee",
    "dangerLine": "#dfbbb7",
    "overlay": "rgb(30 57 50 / 45%)",
    "wechat": "#07c160",
    "mediaMuted": "#eeece8",
    "skeleton": "#e4e4e1"
  },
  "spacing": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "12": 48,
    "16": 64,
    "20": 80,
    "24": 96
  },
  "zIndex": {
    "base": 0,
    "raised": 10,
    "sticky": 20,
    "dropdown": 30,
    "overlay": 40,
    "modal": 50,
    "toast": 60
  }
} as const);
